# This rule is not used by the project controllercountpods itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over count.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controllercountpods
    app.kubernetes.io/managed-by: kustomize
  name: countpod-admin-role
rules:
- apiGroups:
  - count.my.domain
  resources:
  - countpods
  verbs:
  - '*'
- apiGroups:
  - count.my.domain
  resources:
  - countpods/status
  verbs:
  - get
