---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - count.my.domain
  resources:
  - countpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - count.my.domain
  resources:
  - countpods/finalizers
  verbs:
  - update
- apiGroups:
  - count.my.domain
  resources:
  - countpods/status
  verbs:
  - get
  - patch
  - update
